const OK_STATUS = 200;
const CREATED_SUCCESS = 201;
const BAD_REQUEST_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const SERVER_ERROR_CODE = 500;
const FORBIDDEN_REQUEST_CODE = 403;

module.exports = {
  OK_STATUS,
  CREATED_SUCCESS,
  BAD_REQUEST_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  SERVER_ERROR_CODE,
  FORBIDDEN_REQUEST_CODE,
};
